### ISSUE TITLE
Through a series of interviews, we understand the history, current status, and vision for CPG response in Mozilla's communities

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#107]
## Objective Goal: 
*This is a learning task for our new CPG response lead - @musingvirtual :) .**

* Understand how CPG and incident response is currently working (and not working) for community.
* Understand the various types of offenses and reports we’ve dealt with in the past (or are worried about for future).
* Understand culture and history of Mozilla communities

## Item list:
- [ ] Reach out to identified people, and schedule interviews (R: @musingvirtual)
- [ ] Finalize interview script and note taking methods  (R:  @musingvirtual)
- [ ] Complete all interviews (R: @musingvirtual)

**Comment by Rupal-IIITD** [comment]
Hi.

Am I allowed to take up this issue and work?

(Asking because in the description it's written that it is for the CPG lead - Kate.)

**Comment by emmairwin** [comment]
Hi @Rupal-IIITD this one is specifically assigned to @musingvirtual but thank you very much for asking.

**Comment by musingvirtual** [comment]
I have finalized the script and currently have 5 scheduled interviews, 3 of which are this week.

In this upcoming week I am intending to schedule several more interviews for next week, as well as carry out these three interviews and see if I need to iterate on the script.

**Comment by emmairwin** [comment]
This is duplicate of #155
