### ISSUE TITLE
 Proposal for Code of conduct 

### ISSUE THREAD

**Issue by akshitac8** [mozilla/diversity#111]
## Objective Goal: 
It would be nice if we had a code of conduct.
Clearly stating ***acceptable and unacceptable behaviour***

**Comment by akshitac8** [comment]
Should I work on this?

**Comment by musingvirtual** [comment]
HI Akshita, 

Thanks for offering to help!

We in fact do already have a code of conduct for this repository, and it's Mozilla's [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).

Thanks,
Kate

**Comment by akshitac8** [comment]
Ohkay, @musingvirtual :slightly_smiling_face:
