### ISSUE TITLE
Wiki Template for the Diversity in Open Source call

### ISSUE THREAD

**Issue by musingvirtual** [mozilla/diversity#113]
Seeking volunteer contributors for this one - please read our updated [Readme](https://github.com/mozilla/diversity/blob/master/README.md) before contributing.

## Objective Goal: 

Create a wiki template for the [ Diversity in Open Source calls](https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors#D.26I_in_Open_Source_Community_Calls), and populate the template for the two calls that have already happened, and the upcoming May and June calls.

In order to complete this contribution please give us links to your template on the [MozillaWiki](https://wiki.mozilla.org/) - no need to check in any code here. Feel free to ask any questions you need to ask. Doing part but not all of the task is totally okay. 

You will need to [create an account](https://wiki.mozilla.org/Special:RequestAccount) on the Mozilla Wiki and get it approved in order to do this task - this may take about 24h.

## Related documents and links 
* [Directions and info about what we want in a template](https://docs.google.com/document/d/1OZNVxkZgWBl5VgTB1DveyFwziW1aXd-aET_T4nkX6fI/edit#) - you can leave comments in this doc to ask questions and Kate will get back to you.
* [General howto for Media Wiki templates](https://www.mediawiki.org/wiki/Help:Templates)

## Item list:
- Create a template on the Mozilla Wiki that we can use for future Diversity & Open Source Calls.
- Get Kate to review your template and suggest any changes.
- Apply the template to the two past calls.
- Apply the template to the two future calls.

**Comment by akshitac8** [comment]
Hello, @musingvirtual I want to volunteer  :slightly_smiling_face:

**Comment by akshitac8** [comment]
Hey, @musingvirtual I was trying to make a Mozilla wiki account and there is a field for 

`Name of mentor or guide at Mozilla`

What information should I fill in that field?
Thanks.

**Comment by musingvirtual** [comment]
Hi Akshita! Thanks for taking this one on.

You can put my name down (Katherine Mancuso).

**Comment by akshitac8** [comment]
Thank you for the info :smiley:

**Comment by reCursedd** [comment]
Hello,

Can I volunteer for this too?

**Comment by marimeireles** [comment]
Hey, I'd like to help if the girls need any help. :)

**Comment by avneet14027** [comment]
Hey! Can I wok on this too, if needed?

**Comment by musingvirtual** [comment]
Hi everyone - 

Thanks for the enthusiasm! 

I'll let @akshitac8 decide if she would like to work together with others this time. 

Next time I have a task I'll try to divide the task into parts if that's possible so more of you can have a part.

**Comment by akshitac8** [comment]
Hey, I am almost done with the task. @musingvirtual  Will it be feasible to add more people to the final stage?
For future tasks, we can take care that everyone's involvement and ideas are included.

**Comment by akshitac8** [comment]
Hey @musingvirtual 
These are the links to the changes made at Mozilla wiki. It would be great if you could  suggest if any changes needed :smiley: 

https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors

https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors/D%26I_Call_2_28_2018

https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors/D%26I_Call_4_4_2018

https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors/D%26I_Call_5_2_2018

https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors/D%26I_Call_6_6_2018

**Comment by akshitac8** [comment]
Thank you @emmairwin :slightly_smiling_face:

**Comment by akshitac8** [comment]
Is there anything else, I can do here ?? :slightly_smiling_face:
