### ISSUE TITLE
Preparing for Interviews

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#121]
## Objective Goal: 
Leveraging existing resources, and opportunity to talk with knowledge experts, I have prepared for, and begun to setup interviews.

## Related Issues
[Reference meta issues and past issues] #

**Comment by emmairwin** [comment]
Follow up note - to prioritize conversations as discussed.

Also here is link to 'Increasing Rusts Reach'

http://reach.rust-lang.org/

**Comment by musingvirtual** [comment]
Completed!
