### ISSUE TITLE
CPG process is well-documented and consistently followed and we have a baseline for improvements

### ISSUE THREAD

**Issue by musingvirtual** [mozilla/diversity#130]
## Objective Goal: 
Existing CPG process is well-documented and consistently followed on each case, and we iterate on it between cases.

## Related documents and links 
* [CPG Process Workflow and questions](https://docs.google.com/document/d/1_7aOQj9wWWDXGp9_L-pPHN0-zgFMp9F3IGOZl7sFRJc/edit#)
* Existing CPG process is well-documented and consistently followed on each case, and we iterate on it between cases.

## Item list:
- Kate to review notes from last week on CPG process and expand them into something that can be followed more systematically (a checklist? something else?)

## Related Issues

**Comment by emmairwin** [comment]
Hi @musingvirtual 

Where do you want ti file this?   This is the roadmap now I think?

**Comment by musingvirtual** [comment]
This is super old and again is pegged against my 3 month goals and not a particular sprint.

**Comment by emmairwin** [comment]
Does it feel relevant to you still?

**Comment by musingvirtual** [comment]
I think we should close this, because it was from a completely different working framework. It would possibly be good to have our quarterly goals in the repository as some kind of larger framework to map sprints against, but that's not going to be accomplished with a task, that's a completely different object.
