### ISSUE TITLE
Identify Mozillian and Rep data to request from ParSys

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#14]
## Objective Goal: 
Please profile information on mozillians.org and https://reps.mozilla.org/ and create a list of fields to request from participation systems.  Email to me and Mike ( I will forward to Henrick).  The best way to view fields in Mozillians is to go to the edit screen for your profile.

**Comment by bee2502** [comment]
A list of all data attributes in Mozillians and Reps db is[ here.](https://docs.google.com/a/mozilla.com/document/d/1D2FxjgvluupY6u8InVX6Sg3lVBNfnz1xUHZA-NbnrDQ/edit?usp=sharing) Attributes selected for further analysis have been highlighted.

A list of just selected attributes for both Mozillians and Reps with sample questions detailing why they have been selected is[ here](https://docs.google.com/a/mozilla.com/document/d/1D6_BFEqfwjeoryEoOKswZxy7IsMpCyMQ1EjF-zml0Vc/edit?usp=sharing).

**Comment by emmairwin** [comment]
Thank you, consider this completed
