### ISSUE TITLE
Learn about Community Analytics Dashboard 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#149]
## Objective Goal: 
You understand how to navigate, and use the Community Analytics Dashboard, and have documented some early insights into the Dev Tools/Debugger Github community.

Emma to email links

**Comment by akshitac8** [comment]
I am on it :)

**Comment by akshitac8** [comment]
Do I need to write some documentation about the tool or just continue analysing and study its components?

**Comment by emmairwin** [comment]
I would like you to learn about this tool, and then think about ways you could apply to to say learn about a project.  One specific one I would like you to use, is a real case study  we need:

https://github.com/devtools-html/debugger.html

The link I gave you is for this repository.    Steps would be

-[ ] Spend time learning about the tool as a whole (click around, see what it can do, what you can learn.
-[ ] Make a list of things you believe the tool is useful for learning about open source projects, with examples.  This doesn't need to be fancy but would be helpful to us.
-[ ] Specifically focus on the debugger tool, and document your observations about that project that feel interesting.

**Comment by emmairwin** [comment]
@akshitac8 

You definitely do not need to write documentation.   Here is what would be helpful.
Write out the Top 10 most interesting things you learned about devtools-html/debugger.html by looking at the dashboard. 

And for each of those 10, how someone else find that same data (steps to recreate)

Does that make sense?

**Comment by akshitac8** [comment]
Yes, definitely this is really helpful. I will tweak the data added to the list and will update you with the list.

**Comment by emmairwin** [comment]
Hi @akshitac8

Thanks for your work so far!   Here's my next ask :)
Look at only the https://github.com/devtools-html/debugger.html repo.
If you're not sure how to change repos, go into #participationsystems in Slack and ask  - someone will help you.   Then...


I'll email you some next steps.

**Comment by hmitsch** [comment]
Hi @akshitac8,

thanks for looping me into the conversation.

Have you had a look at (some of) this:
https://wiki.mozilla.org/ParticipationSystems/CommunityAnalytics

Also, let's touch base on Slack, I'd hope I can jump on a call with you to look at some of the questions you have in a live conversation with Community Analytics in front of us.

Lastly, I hope you are aware that Susy is trying to arrange a session for us at the All Hands in two weeks. I understand she wanted to invite: you&Emma, herself&Krishna, me

-Henrik

**Comment by akshitac8** [comment]
Thank you @hmitsch for looping in I have replied on slack also and would love to get involved in the conversation.
