### ISSUE TITLE
Generate user stories to fetch data from Bitergia Community Analytics dashboard.

### ISSUE THREAD

**Issue by bee2502** [mozilla/diversity#15]
## Objective Goal: 
Generate user stories to give as input into software/systems team for community analytics as input to software & systems team for review and implementation into software.systems for future data collection & analysis. 

## Related documents and links 
* [Discourse thread 1](/https://discourse.mozilla-community.org/t/analytics-at-open-innovations-participation-systems-team/12262)
* [Discourse thread 2](/https://discourse.mozilla-community.org/t/analytics-at-open-innovations-participation-systems-team/12262)
* [Participation metrics Github Repo](/https://github.com/mozilla/participation-metrics-org)

## Item list:
- [x] Identify attributes we need from Community Analytics dashboard (R:)
- [x] Create atleast 5 user stories for fetching the data for identified attributes (R:)
- [ ] cc Emma and Henrik for feedback (R:)
- [ ] If positive, add user stories as new issues to community analytics repo (R:)

## Related Issues:

* [#523](/https://github.com/mozilla/community-development/issues/523)

**Comment by bee2502** [comment]
Data goals for Community Analytics Dashboard and a list of sample user stories for it is [here.](https://docs.google.com/a/mozilla.com/document/d/1AzMJO7BZOBm75hUYce-c0sECkejrNO-Sn8JRzJdSHLI/edit?usp=sharing) Pending feedback from @mjskang @emmairwin @larissashapiro

**Comment by emmairwin** [comment]
@emmairwin please review and update
