### ISSUE TITLE
Kate to do presentation on SuMO call

### ISSUE THREAD

**Issue by musingvirtual** [mozilla/diversity#152]
## Objective Goal: 
Presentation delivered on SuMO call May 23rd in order to educate SuMO community about CPG.

## Item list:
- [x] @emmairwin to provide link to slides used for reps call (R: @emmairwin )
- [x] Kate to revise slides (R: Kate)
- [x] Kate to give talk (R: Kate)

## Related Issues

**Comment by emmairwin** [comment]
https://docs.google.com/presentation/d/1ZXcSptpFhfWLUDHDY9p0DYbeG3HAvrrbGh26LT9JRlQ/edit?usp=drive_web&ouid=112031452392775547359
