### ISSUE TITLE
Complete Onboarding Steps

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#154]
## Item list:
- [x] You have been added to Open Innovation team, and other Slack channels, please update your profile with full name,  pronouns your profile ( and familiarize yourself with the names and pronouns of others on the team)
- [x] Complete Reading provided in email 
- [x] Make sure you can view Zenhub dashboard, and update tasks accordingly
- [x] Outreach blog post

**Comment by emmairwin** [comment]
great work!

**Comment by akshitac8** [comment]
Thank you :)
