### ISSUE TITLE
Finalize list of 8 for further interview

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#155]
## Item list:

- [x] Finalize script and final 8  (R: @emmairwin @musingvirtual )
- [x] 8 calls are scheduled ( R @musingvirtual )

## Related Issues
[Reference meta issues and past issues] #

**Comment by emmairwin** [comment]
FYI, I have asked Mrinalini to prioritize rescheduling with you when they return.

**Comment by emmairwin** [comment]
update - how many calls have been scheduled>? so we can set goals for next sprint.

**Comment by musingvirtual** [comment]
Basically done with many interviews scheduled for next week (still waiting for Michael Henretty to email me back and let me know it's okay to schedule a time).

**Comment by musingvirtual** [comment]
As per discussion we decided the number of these I've done is enough.
