### ISSUE TITLE
We have identified and prioritized user stories for the systems project, based on the recommendations approved by legal regarding risk.

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#156]
## Item list:
- [x] Emma to propose goals and format for capturing user stories(R: @emmairwin)
- [x] Kate to review and add  (R: @musingvirtual )
- [x] Finalize and prioritize and run by Arielle & Henrik (R: @emmairiwn @musingvirtual )

**Comment by musingvirtual** [comment]
closed since this has happened
