### ISSUE TITLE
A CPG Interface has been proposed and added to Common Voice repository

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#163]
## Objective Goal: 
A CPG Interface has been proposed and added to Common Voice repository

## Item list:
- [ ] Aligned with CPG roadmap goal, and in consultation with  we have created a lightweight proposal for a CPG reporting interface for Common Voice
- [ ] CPG interface is added to Common Voice project

**Comment by musingvirtual** [comment]
Hi Emma - have you collected any requirements for this interface from Michael, or do I need to go do that?

**Comment by emmairwin** [comment]
1) How to flag CPG violations? (what should look for?)
2)How to take a report?    (staff, and contributor version)
3)How to leverage our process. (email Kate/Emma).  - will eventually be a system.

This would be in a markdown file, single , called REPORTING.md

Goal of making this a template other open projects can use like README or CONTRIBUTING. .

**Comment by musingvirtual** [comment]
I am not sure whether I am going to have the time to work on this in this sprint, and this is outside of scope for Q2 goals. 

Can we move this to the backlog, Emma, is there any reason we're doing it now?

**Comment by emmairwin** [comment]
Its in our Q2 goals.

**Comment by emmairwin** [comment]
Completed, instructions and support offer to CV to implement.

https://github.com/mozilla/repo-templates/blob/master/templates/REPORTING.md
