### ISSUE TITLE
Weekly CPG report is proving value to leadership

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#165]
## Objective Goal: 
Sheduled, weekly CPG update is proving value to key stakeholders

## Item list:
- [ ] A scheduled update of CPG cases, with added timeline, and names is provided on a predictable schedule is regularly to  identified stakeholders.(R: @musingvirtual )
- [ ] An email at the end of the quarter, to stakeholder requesting ROTI  results in 4.0 or greater . (R:@musingvirtual )

**Comment by musingvirtual** [comment]
Closing this because I combined it with the other "CPG timelines running" one!
