### ISSUE TITLE
Add community call updates

### ISSUE THREAD

**Issue by drashti4** [mozilla/diversity#171]
## Objective Goal: 
Update community call details with resources.

## Related documents and links 
* [Community call list](https://github.com/mozilla/diversity/blob/master/community-calls/02.27.2018.md)

This is unclear to me. I'm willing that our all community call should be listed in repo but above link is about physical community call only?

**Comment by emmairwin** [comment]
We're currently using the wiki to track calls.

https://wiki.mozilla.org/Diversity_and_Inclusion_for_Communities_and_Contributors#D.26I_in_Open_Source_Community_Calls
