### ISSUE TITLE
Move Onboarding FAQ File to Process Folder

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#174]
Create a new folder called community_comms in this folder:

https://github.com/mozilla/diversity/tree/master/code-of-conduct-enforcement/decisions/communication

Please move:

https://github.com/mozilla/diversity/blob/master/code-of-conduct-enforcement/FAQ%20-%20Contributor.md

into the community_comms folder

**Comment by drashti4** [comment]
Done :+1:
