### ISSUE TITLE
Our D&I Social in Portland (after CLS on June 24th) is setup for success

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#181]
## Objective Goal: 
Our D&I Social in Portland (after CLS on June 14th) is setup for success.
(both Emma and Kate speaking)

## Item list:
- [x] Identify budget, and schedule catering (R: @emmairwin)
- [ ] Identify invite list, including brand  (R: @emmairwin)
- [x] identify speaker(s) for reception (R: @emmairwin)
- [ ] Book travel (@emmairwin, @musingvirtual)
- [ ] Event successfully executed 

## Related Issues
[Reference meta issues and past issues] #

**Comment by musingvirtual** [comment]
I've contacted the travel team and asked them to set up an Egencia account for me.

Also, do you mean July 14th?
