### ISSUE TITLE
Systems Project

### ISSUE THREAD

**Issue by musingvirtual** [mozilla/diversity#182]
## Objective Goal: 

Documentation is prepared for the systems evaluation, and steps are taken toward figuring out who needs to be involved and generating a proposed timeline based on this. Goal is for signoff July 30th - is this manageable?

## Item list:

Hazel - Drafting documentation:
- [x] Create first draft of edited user story matrix (R: Kate)
- [x] Once user stories chosen evaluate the 3 tools we've already looked at against them (R: Kate)
- [x] Add Navex Global and another piece of compliance software based on their website (R: Kate)
- [x] Write narrative recommendation for Convercent and future work with Callisto (R: Kate)

Evergreen - Understanding the timeline and budget - overall goal is to have a timeline and a budget figure by the time we get our procurement doc signed off.

- [ ] Schedule follow-up call with Convercent (R: Kate)
- [ ] Kate to meet with Sean in IT to find out what the path to implementation here is and who needs to be consulted/involved from that department. (R: Kate)
- [ ] Survey from "what is scale" will produce names of the community managers who want to be consulted (R: Kate)
- [ ] Kate to meet with Bob in procurement/CASA to understand how long this part takes (R: Kate)
- [ ] Kate to begin consulting people on stakeholder list for signoff. (R: Kate)

## Related Issues
#167

**Comment by akshitac8** [comment]
Do let me know if I can volunteer on this anywhere in this, if possible :)

**Comment by musingvirtual** [comment]
Moving to next sprint and adding some stuff :)
