### ISSUE TITLE
CPG Roadmap is SIgned off by Key Stakeholders

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#185]
## Objective Goal: 
CPG Roadmap is SIgned off by Key Stakeholders

## Item list:
- [ ] Kate, Emma to review for final missing pieces based on recent conversations/All Hands (R: @musingvirtual
- [ ] Emma to review for resources with Lucy (is this timeline realistic!)(R: @emmairwin)

## Related Issues
[Reference meta issues and past issues] #

**Comment by musingvirtual** [comment]
Hi @emmairwin - am I correct in thinking we completed this?

**Comment by emmairwin** [comment]
yes!  Closing
