### ISSUE TITLE
Womoz Safe Channel, Learning Synthesized, and Next Steps Proposed

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#186]
## Objective Goal: 
With synthesized learning, and based on All Hands, and in collaboration with Delphine, propose next steps to L10N and Community Development teams for safe channels

## Item list:
- [ ] Emma to write up learning and recommendations 
- [ ] Iteration of those with Delphine
- [ ] Delphine and Emma to submit to L10N and Comm Dev teams for approval

## Related Issues
[Reference meta issues and past issues] #

**Comment by akshitac8** [comment]
Can I help here :slightly_smiling_face:
