### ISSUE TITLE
Building FAQ for conducting First Language Interviews

### ISSUE THREAD

**Issue by bee2502** [mozilla/diversity#19]
## Objective Goal: 
Building FAQ for conducting First Language Interviews

## Related documents and links 
* [Links here](/thelink)

## Item list:
- [x] Compile a list of all resources available for assisting with conducting first language interviews (R: Kristi, Nasma, Bee)
- [x] Compile a FAQ to help first language interviewers get started (R: Kristi, Bee)
- [x] Collect feedback on FAQ from first language interviewers and ask them to add their experiences (R:)
- [x] Publish the FAQ to wiki with links to other resources. (R:)

## Related Issues
* [#4](/https://github.com/mozilla/diversity/issues/4)

**Comment by bee2502** [comment]
@emmairwin , I am not able to assign this to Kristi and Nasma. Also, I cannot even tag them in comments. Can you look into this please ?

**Comment by kristiprogri** [comment]
Will be sending the FAQ for review today.

**Comment by bee2502** [comment]
We have a preliminary draft for FAQ [here.](https://docs.google.com/a/mozilla.com/document/d/1gs0m01RMXXrqYEaZcuyNNu49WAMS2Zlmhhl0cHdAemE/edit?usp=sharing) This can be added to wiki as a resource, post review.

**Comment by bee2502** [comment]
@kristiprogri Please assign this issue to yourself too. I am not sure why I can't.

**Comment by bee2502** [comment]
The wiki page is [here.](https://wiki.mozilla.org/Diversity_and_Inclusion_Strategy:First_Language_Interviews_FAQ)
