### ISSUE TITLE
Tool to evaluate the PR Quality

### ISSUE THREAD

**Issue by akshitac8** [mozilla/diversity#195]
- [x] State the tools that can be used to evaluate the PR quality.

**Comment by akshitac8** [comment]
Some of the tools to evaluate PR includes:
 - [ ] Travis 
 - [ ] pep8 speaks
 - [ ] review-bot
 - [ ] sentiment-bot

**Comment by akshitac8** [comment]
@emmairwin Do let me know your views? :smiley:

**Comment by emmairwin** [comment]
I am only interested in what you think we should know about, and why :) if you have time . Prototype is priority.

**Comment by akshitac8** [comment]
Ohkay, I am up for sentiment bot :)

**Comment by akshitac8** [comment]
We need to install this for the Diversity Repo 
https://github.com/apps/sentiment-bot
to make the review process a bit easy. 
@emmairwin  Do let me know if any problems occur :)
