### ISSUE TITLE
Communication Templates for CPG Enforcement 

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#216]
- [ ] "So you're on a CPG RASCI"  - generic onboarding text for email to what/why/when/where/who.   
- [ ]  "You're in a CPG Case" - generic email for comms with specific about timeline, what to expect, when, where.  (with placeholders for those)

Will add more.

**Comment by emmairwin** [comment]
Added Contributor wanted, if you are interested in learning about our CPG (CoC) process, this is a good way.

**Comment by joopeed** [comment]
Hi @emmairwin, can I get more detail on this one, please?

**Comment by emmairwin** [comment]
sorry this was outdated.
