### ISSUE TITLE
Retaining woman in open source: Organising open source day montly

### ISSUE THREAD

**Issue by tapaswenipathak** [mozilla/diversity#226]
Hi folks: Finding an active open source contributor or maintainer woman is hard. Internships give a break in open source, if observed there is no retention of women in open source and research[1] suggests. Implementing open source day per month letting woman work with mentor and contribute in an open source project they would like would be practical implementation than just publishing research and articles. Lemme know if you would interested in supporting and I will share further information.

[1] https://en.wikipedia.org/wiki/Diversity_in_open-source_software

**Comment by emmairwin** [comment]
I am sorry I did not see this before!   
I suggest, that you post this to https://groups.google.com/forum/#!members/diversity--inclusion-in-open-source   I can help support, by way of goal-setting
