### ISSUE TITLE
Build overall framework to describe the analysis strategy/ process we are in now 

### ISSUE THREAD

**Issue by mjskang** [mozilla/diversity#23]
## Objective Goal: 
The data analysis process is confusing has many facets.  The goal is to create an overall framework to help clarify the process we are in now, where it is going, and what its inputs are. 

## Related documents and links 
* Draft framework (work in progress) is here: https://docs.google.com/document/d/1gjyQ4FpAqULjBIbMdDzYPAVDOravyNOrkA4iPocWJ6s/edit)

## Item list:
- Draft and share framework

**Comment by bee2502** [comment]
Hi @mjskang, I cannot access the link in this issue for framework draft.

**Comment by mjskang** [comment]
Yep - sorry I am revising it today.  Will share the correct link ASAP!
