### ISSUE TITLE
Are you serious?

### ISSUE THREAD

**Issue by lazaridiscom** [mozilla/diversity#240]
from: https://github.com/mozilla/diversity/blob/master/evaluation_tools/contributor-testing-steps.md

> Community Actions ( 15 minutes)
> 
>     Find the Code of Conduct.
>     Find information on the community leaders and staff.
>     Log into the chat channel and say hi.
>     Review the contributing document (CONTRIBUTING.md usually, but sometimes the README.md)

What do you address? Monkeys? "log into the chat channel and say hi".

You discriminate and exclude higher-grade thinkers, which give not even a piece of trash for all this redundant overhead.

The "Code of Conducts" cannot withstand any evaluation, it is a pure insult, discriminating in itself.

On what level do you think?

Common Law deals already with everything redundantly stated int the Code of Conduct.

## Super-Market-Code of Conduct

"When you go into the supermarket, don't stab other people with a knife, simply because you don't like how they look, speak, smell, talk, move (extensive list)"

**Comment by emmairwin** [comment]
Hey @lazaridiscom , with account created 15 days ago.
This is not an assessment of contributor intelligence, but a script for testing project ready-ness for contributors. IF someone says 'hi' and no one responds, it doesn't really matter if they are a 'higher grade thinker'.  

If you read the intro 'he intention is to see how well a project is setup to accommodate those without luxury of hours of time to figure things out.'  you'll learn that.

Thanks

**Comment by lazaridiscom** [comment]
Comment-close.

I've learned all I wanted to learn.

No wonder Mozilla is falling more and more behind.
