### ISSUE TITLE
First language interview with two Mozillians

### ISSUE THREAD

**Issue by psubhashish** [mozilla/diversity#3]
## Objective Goal: 
Conducting first language interview (in [Telugu-language)](https://en.wikipedia.org/wiki/Telugu_language) with two Mozillians by February 21

## Item list:
- [x] Identifying a first language interviewer and a notetaker (Dyvik Chenna and Deepak Upendra selected) (R: @psubhashish )
- [x] Getting the script translated (thanks to Dyvik and Deepak) (R: @psubhashish )
- [x] Interviewees are selected and briefed about the interview (by Dyvik and Deepak) (R: @psubhashish )
- [x] Conducting the interview (Dyvik and Deepak) (R: @psubhashish )
- [x] Translating interviews in English (Dyvik and Deepak will share by 02/28 - delayed as both were traveling) (R: @psubhashish )

## Related Issues
* [ #524](https://github.com/mozilla/community-development/issues/524)

**Comment by emmairwin** [comment]
@psubhashish who is doing the interviews?

**Comment by psubhashish** [comment]
@emmairwin It's Dyvik, a Rep from Hyderabad. I have sent him the the script and am waiting for the translation.
