### ISSUE TITLE
1-2 first language interviews

### ISSUE THREAD

**Issue by psubhashish** [mozilla/diversity#35]
## Objective Goal: 
1-2 interview by this week.

## Related documents and links 
* [Links here](/thelink)

## Item list:
- [x] Interviewees identified (R: @psubhashish )
- [x] Script translated (R: @psubhashish )
- [x] Interviews conducted
- [x] Field notes [translated](https://docs.google.com/document/d/17erekLihOTMu5nWOfIJueNMeF2FM6_zsr3xoKocfpxs/edit) (R: @psubhashish )

Note
----
Planned to conduct one more interview but could not do that as the interviewee was not available

## Related Issues
[Reference meta issues and past issues] #

**Comment by emmairwin** [comment]
Hi @psubhashish please ensure you add milelstones and tags when you crete these, so we know if they are work you intend to do this week, and the priority.  Can you also please elaborate on your target group for this interview?   Can I suggest people working in the open, who might know about accessibility?

**Comment by psubhashish** [comment]
@emmairwin this was an individual interview. I will certainly update the tags.

**Comment by emmairwin** [comment]
Can you tell me what you need reviewed?  Thank you

**Comment by psubhashish** [comment]
@emmairwin I submitted the outcome of the interview so marked as "Review needed".
