### ISSUE TITLE
Goals for week (Feb 13th-Feb19th)

### ISSUE THREAD

**Issue by kristiprogri** [mozilla/diversity#4]
## Objective Goal: 
Finish my blogpost, translating interviews in English, translating all scripts in Albanian, FAQ.

## Related documents and links 
* [<a href="http://kristiprogri.com/">kristiprogri.com</a>]
   [<a href="https://docs.google.com/document/d/1Y94l4oT2GjqSdj0s3ZuHSmQWwXCC3lcBfsjPBNxurYY/edit?ts=58a1b116/">https://docs.google.com/document/d/1Y94l4oT2GjqSdj0s3ZuHSmQWwXCC3lcBfsjPBNxurYY/edit?ts=58a1b116/</a>]

## Item list:
- [x] Finish my blogpost.
- [x] I took some interviews from the contacts I got in FOSDEM , should upload them
- [x] Translating the scripts in Albanian language, so everyone who want to help me from local community can find it easier.
- [x] Translating the interviews I got from 3 interviews 1:1 and 1 focus group.
 -[ ] Review the FAQ and release it as soon as possible (R: @bee2502 ) 

## Related Issues
[Reference meta issues and past issues] #

**Comment by emmairwin** [comment]
Hi Kristy please update this as in progress, or completed.   Thank you
