### ISSUE TITLE
Analyze and report on remaining data sources 

### ISSUE THREAD

**Issue by mjskang** [mozilla/diversity#40]
## Objective Goal: 
Extract critical insight from remaining data sources.  

## Related documents and links 
*All data progress is tracked here:  https://docs.google.com/spreadsheets/d/1G-GwPZQcAR7muVXMCiCEI-8a5ULErx70wAhDo_P860g/edit?ts=58a6fcd4#gid=0

## Item list:
- [ ] All Global Events Combined  - Mike
- [ ] MozFest - Mike
- [ ] Leadership Summit  - Mike
- [ ] European Gathering Registration - Bee
- [ ] Arabic - Community Gathering  - Bee
- [ ] India Community Meetup - Bee
- [ ] Regional Community Survey - Mike
- [ ] WoMoz Survey - Vision, Progress, Community Building (Responses) - Bee
- [ ] Rust Community Analytics Dashboard - Mike
- [ ] Google analytics - Mike
- [ ] Firefox data  - Mike
- [ ] Contributor Audit Data - Mike
- [ ] Rust data  - Mike
- [ ] Mozilla Sentiment Survey (SurveyMonkey How are we Doing) - Bee
- [ ] SurveyMonkey - Reps Budget Procedure Survey - Bee
- [ ] SurveyMonkey - Reps Budget Procedure Survey - end of Q4 - Bee

## Related Issues
[Reference meta issues and past issues] #

**Comment by bee2502** [comment]
Analysis has been shared and used in Design Sprint at Canada.
