### ISSUE TITLE
A Blog for Mother Language Day is published reflecting inspiring work with first language interviews

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#5]
## Objective Goal: 
Blog post posted Feb 21

## Item list:
- [x] collect [stories](https://docs.google.com/document/d/1q6edoKs0NVNK1aPxAybuBNkYraq2qvP-JgXA36qQ-tE/edit), [photos](https://drive.google.com/drive/u/1/folders/0B7mlsiMB0h-9RHlxYWJxZEZMZGc) related to first language interviews (R: @psubhashish @emmairwin)
- [x] Created a [email template](https://docs.google.com/document/d/1o0pEBbqLAyll_5ngWDWI5t_v8NJ3VAg6Y3DZhl5EhVc/edit) for relicensing images/other works to be used under a free license
- [ ] write and publish post (R: @emmairwin)

**Comment by emmairwin** [comment]
@psubhashish I put this as a task so we don't lose it as a goal, I am offering to write post if you can help me collect content?  Does this sound oK?

**Comment by psubhashish** [comment]
@emmairwin yes, absolutely, and thanks for following up on this. I will try to gather some narratives that will fit well for the IMLD.
