### ISSUE TITLE
Learn about FOSS Heartbeat

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#83]
## Objective Goal: 
We have a set of standards and frameworks that let us accurately understand the impact of our D&I interventions on the health of open source communities.  

To help this goal, we will be working more with FOSS Heartbeat, which evaluates sentiment in Github issues, comments and pull requests!

**NOTE**: multiple people can work on this task.

## Item list:
- [ ] Following the steps in the [README](https://github.com/emmairwin/foss-heartbeat/blob/master/README.md), build the environment (including sentiment) for [FOSS Heartbeat](https://github.com/emmairwin/foss-heartbeat) and test on one Github repository. 
- [ ]  Commit your work back to Heartbeat, or share screenshots of the results.

**Comment by emmairwin** [comment]
Note that this project does have known bugs with some repositories, one that we've tested recently that works is:   https://github.com/mozilla-l10n/documentation

**Comment by emmairwin** [comment]
Hi @marimeireles please do!   If you get stuck please ping me.

**Comment by Nada1996** [comment]
Hi @emmairwin ,  can I work on this too?

**Comment by emmairwin** [comment]
Hi @Nada1996 yes!    Just make sure you test with the Github repository I listed first ( as a way to ensure your environment works), and then any Github repository you are interested in afterwards.  Please let me know if you have get stuck!

**Comment by ruchaapte** [comment]
Hi Emma, I would like to work on this for outreachy. Can I contribute towards it?

**Comment by ruchaapte** [comment]
I had a question. After setting up the environment, I'm trying to scrape data from the given repository using the command
python ghscraper.py GITHUB_REPO_NAME GITHUB_OWNER_NAME FILE_WITH_CREDENTIALS
I'm not sure what the GITHUB_OWNER_NAME would be here. Could you please help me on this? 
Also, I have specified my github username and password in separate lines in a file for the credentials. Is that the correct approach?
I am trying to run it this way:
python ghscraper.py documentation mozilla-l10n ../pass.txt

**Comment by joanasouza** [comment]
Hey @ruchaapte I think that I can help you with that. 
To run the command you're going to use the exact path of the repo you're testing. 
The GITHUB_OWNER_NAME refers to the github account that originally owns the repo.
In one of my tests I ran this command with Mozilla lightbeam repo, then my command looked like this: 
python ghscrapper.py lightbeam-we mozilla <my_generated_token>.
About the file question I think you're doing in the right way but I am not sure enough because when I tried I used a Token. If you still need help with I can try at home using a file

**Comment by ruchaapte** [comment]
Thanks @joanasouza for the help. When I run the command for any github repo, I get an error . 
  File "ghscraper.py", line 108, in scrapeIssues
    issues = repo.issues(sort='created', direction='asc', state='all',
AttributeError: 'Repository' object has no attribute 'issues'
Did anyone face this?

**Comment by marimeireles** [comment]
Hi @emmairwin I've just completed the tests using the mozilla-l10n/documentation and the mozilla/DeepSpeech repositories and pushed to a branch [here](https://github.com/marimeireles/foss-heartbeat/tree/deepspeech-l10n). 
It wasn't clear to me if I was supposed to open a pull request in the [foss heartbeat](https://github.com/sagesharp/foss-heartbeat) repo and merge that, should I do that?

I've also noticed a minor CSS error in some of the graphics generated by plot.ly like this one:
![screenshot from 2018-03-09 23-14-52](https://user-images.githubusercontent.com/17600982/37237229-baf35f72-23ef-11e8-9ce3-362ccf09af48.png)
I don't know if it's a relevant error, but if you want to fix it, I'd be happy to help!

Do you have any leads for me? I was thinking about taking some other issues, is this okay?

Thanks!

**Comment by emmairwin** [comment]
@ruchaapte sorry for delay!  and thanks for jumping in @marimeireles 

I used a token as well, it's really easy to do  :  https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
This is the command I used:  python ghcategorize.py documentation mozilla-l10n   <tokenid>

I hope this helps!

**Comment by emmairwin** [comment]
Hi  @ marimeireles   I noticed the files in Deep Speech (which I was super intersted in thank you! ) were for L10N
https://github.com/marimeireles/foss-heartbeat/tree/deepspeech-l10n/docs/mozilla/DeepSpeech

Yes please do submit a PR, and also CSS fixes very welcome!  
There are some Mozilla developers working on existing bugs in this project and your knowledge and observations are super helpful!  thank you!

**Comment by emmairwin** [comment]
@Nada1996 the main purpose of this task is to learn the project, and how the machine learning works for sentiment especially.   
You do not need to create a PR if you ran this only for the l10N documentation repo, but if you run this on other repos you're interested in, then I am sure the maintainer would be interested.

I would be interested in seeing any of active Mozilla repos from this list:

https://github.com/mozilla?utf8=%E2%9C%93&q=firefox&type=&language=
https://github.com/mozilla?utf8=%E2%9C%93&q=rust&type=&language=

We want to see how much this tool can help us understand how healthy communities are, and also your obersvations about what is working, not working - what would make it better would be super, super helpful!  Thank you

**Comment by Nada1996** [comment]
@emma Ok thanks a lot, I did try it on another repo and I will run it on other repos from the list.
 One last thing though, after running the sentiment analysis model on the comments I wanted to plot the graphs for it but according to [#46 ](https://github.com/sagesharp/foss-heartbeat/issues/46) , it's not documented, so do you know which command to run and maybe I can add that to the Fossheart documentation too.
Thanks again.

**Comment by marimeireles** [comment]
Hi @emmairwin 
I don't think there are any relation between the data I've published and the l10n team. You were probably just confused by my bad branch name, sorry, I'll change that.
But since you're interested in how the Deep Speech is related to the l10n project, I'll add some data about the [common voice project](https://github.com/mozilla/voice-web) too, I've been contributing to the Brazilian l10n team to localize it to pt-br and there are other languages being add too. It should have some interesting data.

I'll look into the CSS bugs.

Thanks for the feedback! :)

**Comment by Nada1996** [comment]
@emmairwin I pushed the results to my fork of foss-heartbeat [here](https://github.com/Nada1996/foss-heartbeat) , I tested 3 repos : Mozilla-l10n/documentation, mozilla/node-firefox and rails-girls-summer-of-code/rgsoc-teams	
I will submit a PR to Foss-heart. Thanks

**Comment by emmairwin** [comment]
@marimeireles fantastic!
@Nada1996 I am just going through those now - looks good!

**Comment by emmairwin** [comment]
A note to everyone! that an accepted Pull Request is NOT needed to be considered for successful contribution here.   That you submitted one is all I need.  Thank yoU!

**Comment by emmairwin** [comment]
@sagesharp we are working on improvements FOSS heartbeat in this next quarter.  So it;s relevant to the work we are doing.

I will instead direct people to a fork for now, sorry for the inconvenience.

**Comment by emmairwin** [comment]
Closing and replacing with an updated version:  https://github.com/mozilla/diversity/issues/89
