### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by emmairwin** [mozilla/diversity#94]
Typo in:

https://github.com/mozilla/diversity/blob/master/data-metrics/surveys/en/gender-identity.md
 [cotributor/employees]
should be contributor/employee

**Comment by akshitac8** [comment]
Hey @emmairwin I would like to work on this.

**Comment by akshitac8** [comment]
Hey @emmairwin I have generated a PR #97 for the same.

**Comment by Rupal-IIITD** [comment]
@emmairwin

Hi, Emma.
I would also like to work on it, if I can get some pointers to proceed?
